[package]
name = "cella-wayland"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rustix.workspace = true
thiserror.workspace = true
tracing.workspace = true
wayland-protocols = { workspace = true, features = ["server", "staging"] }
wayland-protocols-wlr = { workspace = true, features = ["server"] }
wayland-server.workspace = true

[dev-dependencies]
arboard = { workspace = true, features = ["wayland-data-control"] }
wayland-client.workspace = true
wayland-protocols = { workspace = true, features = ["client"] }
wl-clipboard-rs.workspace = true

[lints]
workspace = true
