//! `cella features test` — run devcontainer feature tests.
//!
//! Faithful port of the official `devcontainer features test` command.
//! Ref: <https://github.com/devcontainers/cli/blob/main/src/spec-node/testCommandImpl.ts>

use std::collections::HashMap;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::pin::Pin;

use clap::Args;
use serde_json::Value;

/// Embedded test helper library injected into each test container.
const TEST_LIB_CONTENT: &str = r#"#!/bin/bash
SCRIPT_FOLDER="$(cd "$(dirname $0)" && pwd)"
USERNAME=${1:-root}

if [ -z $HOME ]; then
    HOME="/root"
fi

FAILED=()

echoStderr()
{
    echo "$@" 1>&2
}

check() {
    LABEL=$1
    shift
    echo -e "\n"
    echo -e "🔄 Testing '$LABEL'"
    echo -e '\033[37m'
    if "$@"; then
        echo -e "\n"
        echo "✅  Passed '$LABEL'!"
        return 0
    else
        echo -e "\n"
        echoStderr "❌ $LABEL check failed."
        FAILED+=("$LABEL")
        return 1
    fi
}

checkMultiple() {
    PASSED=0
    LABEL="$1"
    echo -e "\n"
    echo -e "🔄 Testing '$LABEL'."
    shift; MINIMUMPASSED=$1
    shift; EXPRESSION="$1"
    while [ "$EXPRESSION" != "" ]; do
        if $EXPRESSION; then ((PASSED+=1)); fi
        shift; EXPRESSION=$1
    done
    if [ $PASSED -ge $MINIMUMPASSED ]; then
        echo -e "\n"
        echo "✅ Passed!"
        return 0
    else
        echo -e "\n"
        echoStderr "❌ '$LABEL' check failed."
        FAILED+=("$LABEL")
        return 1
    fi
}

reportResults() {
    if [ ${#FAILED[@]} -ne 0 ]; then
        echo -e "\n"
        echoStderr "💥  Failed tests: ${FAILED[@]}"
        exit 1
    else
        echo -e "\n"
        echo -e "Test Passed!"
        exit 0
    fi
}
"#;

/// Log level for test output.
#[derive(Clone, clap::ValueEnum)]
pub enum TestLogLevel {
    Info,
    Debug,
    Trace,
}

/// Scenario-scope selectors for `features test`.
///
/// Separated from [`TestArgs`] to keep its bool-field count under
/// `clippy::struct_excessive_bools`.
#[derive(Args)]
pub struct TestScopeArgs {
    /// Run only `test/_global` scenarios.
    #[arg(long, conflicts_with = "features")]
    pub global_scenarios_only: bool,

    /// Skip all scenario tests.
    #[arg(long, conflicts_with = "global_scenarios_only")]
    pub skip_scenarios: bool,

    /// Skip autogenerated `test.sh` tests.
    #[arg(long)]
    pub skip_autogenerated: bool,
}

/// Duplicate-test flags for `features test` (CLI surface parity; execution
/// is deferred — these flags are accepted but duplicate tests are not yet run).
///
/// Separated from [`TestArgs`] to keep its bool-field count under
/// `clippy::struct_excessive_bools`.
#[derive(Args)]
pub struct TestDuplicateArgs {
    /// Skip `duplicate.sh` tests (flag accepted for CLI surface parity).
    #[arg(long)]
    pub skip_duplicated: bool,

    /// Allow random option selection in duplicate tests (CLI surface parity).
    #[arg(long)]
    pub permit_randomization: bool,
}

/// Run devcontainer feature tests.
#[derive(Args)]
pub struct TestArgs {
    /// Path to the project folder containing `src/` and `test/` subdirectories.
    #[arg(long, short = 'p', default_value = ".")]
    pub project_folder: PathBuf,

    /// DEPRECATED: use `--project-folder` instead.
    #[arg(long, hide = true, default_value = ".")]
    pub target: PathBuf,

    /// Feature ID(s) to test (omit to test all features).
    #[arg(long = "features", short = 'f')]
    pub features: Vec<String>,

    /// Filter scenarios by name substring.
    #[arg(long, conflicts_with = "skip_scenarios")]
    pub filter: Option<String>,

    /// Base image for autogenerated tests.
    #[arg(long, short = 'i', default_value = "ubuntu:focal")]
    pub base_image: String,

    /// Remote user for autogenerated tests.
    #[arg(long, short = 'u')]
    pub remote_user: Option<String>,

    /// Log level for test output.
    #[arg(long, value_enum, default_value = "info")]
    pub log_level: TestLogLevel,

    /// Preserve test containers after run (skip cleanup).
    #[arg(long)]
    pub preserve_test_containers: bool,

    /// Suppress output.
    #[arg(long, short = 'q', default_value_t = false)]
    pub quiet: bool,

    #[command(flatten)]
    pub scope: TestScopeArgs,

    #[command(flatten)]
    pub duplicate: TestDuplicateArgs,

    #[command(flatten)]
    pub backend: crate::backend::BackendArgs,
}

/// A single test result entry.
#[derive(Debug)]
struct TestResult {
    label: String,
    passed: bool,
}

/// Collected results for a feature's test run.
struct FeatureResults {
    results: Vec<TestResult>,
}

impl TestArgs {
    /// Execute the `features test` command.
    ///
    /// # Errors
    ///
    /// Returns an error if the project structure is invalid, container
    /// operations fail, or a test script is not found.
    pub async fn execute(self) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        // Resolve the project folder: --target is deprecated but has the same
        // default ("."), so --project-folder wins unless it was left at default
        // and --target was explicitly given (both default to "." so there is no
        // reliable way to detect which one was provided; use project_folder as
        // the authoritative source, matching the official CLI).
        let project_folder = self.project_folder.canonicalize().map_err(|e| {
            format!(
                "Cannot resolve project folder '{}': {e}",
                self.project_folder.display()
            )
        })?;

        let src_dir = project_folder.join("src");
        let test_dir = project_folder.join("test");

        if !src_dir.is_dir() {
            return Err(format!(
                "No 'src/' directory found in '{}'",
                project_folder.display()
            )
            .into());
        }
        if !test_dir.is_dir() {
            return Err(format!(
                "No 'test/' directory found in '{}'",
                project_folder.display()
            )
            .into());
        }

        let client = self.backend.resolve_client().await?;
        client.ping().await?;

        // Discover feature IDs from src/ unless --features was given.
        let feature_ids = if self.features.is_empty() {
            discover_feature_ids(&src_dir)?
        } else {
            self.features.clone()
        };

        let mut all_results: Vec<FeatureResults> = Vec::new();
        let mut global_results: Vec<TestResult> = Vec::new();

        // Run per-feature tests unless only global scenarios were requested.
        if !self.scope.global_scenarios_only {
            for feature_id in &feature_ids {
                let opts = FeatureTestOptions {
                    base_image: &self.base_image,
                    remote_user: self.remote_user.as_deref(),
                    filter: self.filter.as_deref(),
                    skip_autogenerated: self.scope.skip_autogenerated,
                    skip_scenarios: self.scope.skip_scenarios,
                    run_flags: RunFlags {
                        quiet: self.quiet,
                        preserve_test_containers: self.preserve_test_containers,
                    },
                };
                let results =
                    run_feature_tests(client.as_ref(), &project_folder, feature_id, &opts).await?;
                all_results.push(FeatureResults { results });
            }
        }

        // Run global scenarios if they exist (unless --skip-scenarios).
        if !self.scope.skip_scenarios {
            let global_scenarios_json = test_dir.join("_global").join("scenarios.json");
            if global_scenarios_json.is_file() {
                let global_run_flags = RunFlags {
                    quiet: self.quiet,
                    preserve_test_containers: self.preserve_test_containers,
                };
                global_results = run_global_scenarios(
                    client.as_ref(),
                    &project_folder,
                    &test_dir.join("_global"),
                    self.filter.as_deref(),
                    &global_run_flags,
                )
                .await?;
            }
        }

        // Cleanup test containers.
        if !self.preserve_test_containers {
            cleanup_test_containers(client.as_ref()).await;
        }

        // Print results table.
        print_results_table(&all_results, &global_results, self.quiet);

        let all_passed = all_results
            .iter()
            .all(|fr| fr.results.iter().all(|r| r.passed))
            && global_results.iter().all(|r| r.passed);

        if all_passed {
            Ok(())
        } else {
            std::process::exit(1);
        }
    }
}

/// Discover feature IDs from `src/` by listing subdirectories that contain a
/// `devcontainer-feature.json`.
fn discover_feature_ids(
    src_dir: &Path,
) -> Result<Vec<String>, Box<dyn std::error::Error + Send + Sync>> {
    let mut ids = Vec::new();
    for entry in std::fs::read_dir(src_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir()
            && path.join("devcontainer-feature.json").is_file()
            && let Some(name) = path.file_name().and_then(|n| n.to_str())
        {
            ids.push(name.to_string());
        }
    }
    ids.sort();
    Ok(ids)
}

/// Run-time flags passed into scenario and global test runners.
///
/// Kept separate from [`FeatureTestOptions`] so neither struct exceeds
/// `clippy::struct_excessive_bools` (max 3 bools per struct).
struct RunFlags {
    quiet: bool,
    preserve_test_containers: bool,
}

/// Options controlling a single feature's test run (bundles the per-test
/// scalar knobs so `run_feature_tests` stays under the argument-count limit).
struct FeatureTestOptions<'a> {
    base_image: &'a str,
    remote_user: Option<&'a str>,
    filter: Option<&'a str>,
    skip_autogenerated: bool,
    skip_scenarios: bool,
    run_flags: RunFlags,
}

/// Run all tests for a single feature: autogenerated, then scenarios.
async fn run_feature_tests(
    client: &dyn cella_backend::ContainerBackend,
    project_folder: &Path,
    feature_id: &str,
    opts: &FeatureTestOptions<'_>,
) -> Result<Vec<TestResult>, Box<dyn std::error::Error + Send + Sync>> {
    let mut results = Vec::new();

    // Autogenerated test.sh
    if !opts.skip_autogenerated {
        let test_sh = project_folder.join("test").join(feature_id).join("test.sh");
        if test_sh.is_file() {
            let label = format!("{feature_id}/test.sh (autogenerated)");
            if !opts.run_flags.quiet {
                println!("\n▶  Running {label}");
            }
            let passed = run_autogenerated_test(
                client,
                project_folder,
                feature_id,
                opts.base_image,
                opts.remote_user,
                opts.run_flags.quiet,
                opts.run_flags.preserve_test_containers,
            )
            .await?;
            results.push(TestResult { label, passed });
        }
    }

    // Scenario tests
    if !opts.skip_scenarios {
        let scenarios_json = project_folder
            .join("test")
            .join(feature_id)
            .join("scenarios.json");
        if scenarios_json.is_file() {
            let raw = std::fs::read_to_string(&scenarios_json)
                .map_err(|e| format!("Cannot read {}: {e}", scenarios_json.display()))?;
            let scenarios = parse_scenarios(&raw)?;
            let test_dir = project_folder.join("test").join(feature_id);
            let scenario_results = run_scenarios(
                client,
                project_folder,
                feature_id,
                &scenarios,
                &test_dir,
                opts.filter,
                &opts.run_flags,
            )
            .await?;
            results.extend(scenario_results);
        }
    }

    Ok(results)
}

/// Parse a `scenarios.json` file into a map of scenario-name to
/// `DevContainerConfig`.
fn parse_scenarios(
    raw: &str,
) -> Result<HashMap<String, Value>, Box<dyn std::error::Error + Send + Sync>> {
    let value: Value =
        serde_json::from_str(raw).map_err(|e| format!("Invalid JSON in scenarios.json: {e}"))?;
    let obj = value
        .as_object()
        .ok_or("scenarios.json must be a JSON object")?;
    Ok(obj.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
}

/// Filter a scenario map by an optional name-substring filter.
fn filter_scenarios<'a>(
    scenarios: &'a HashMap<String, Value>,
    filter: Option<&str>,
) -> Vec<(&'a str, &'a Value)> {
    let mut entries: Vec<(&str, &Value)> = scenarios
        .iter()
        .filter(|(name, _)| filter.is_none_or(|f| name.contains(f)))
        .map(|(k, v)| (k.as_str(), v))
        .collect();
    entries.sort_by_key(|(name, _)| *name);
    entries
}

/// Run the autogenerated `test.sh` for a feature.
async fn run_autogenerated_test(
    client: &dyn cella_backend::ContainerBackend,
    project_folder: &Path,
    feature_id: &str,
    base_image: &str,
    remote_user: Option<&str>,
    quiet: bool,
    preserve_test_containers: bool,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    let workspace = build_test_workspace(project_folder, feature_id, base_image, &[])?;

    let container_id = bring_up_test_container(client, &workspace, remote_user).await?;

    let workspace_folder = format!("/workspaces/{}", workspace.dir_name);
    let result = inject_and_run_test(
        client,
        &container_id,
        project_folder,
        feature_id,
        &workspace_folder,
        "test.sh",
        quiet,
    )
    .await;

    // Always clean up this container unless explicitly preserved — even on error.
    if !preserve_test_containers {
        let _ = client.remove_container(&container_id, false).await;
    }
    cleanup_workspace(&workspace)?;
    result
}

/// Run all scenario tests for a feature, returning one `TestResult` per scenario.
async fn run_scenarios(
    client: &dyn cella_backend::ContainerBackend,
    project_folder: &Path,
    feature_id: &str,
    scenarios: &HashMap<String, Value>,
    test_dir: &Path,
    filter: Option<&str>,
    flags: &RunFlags,
) -> Result<Vec<TestResult>, Box<dyn std::error::Error + Send + Sync>> {
    let filtered = filter_scenarios(scenarios, filter);
    let mut results = Vec::new();

    for (scenario_name, scenario_config) in filtered {
        let label = format!("{feature_id}/{scenario_name}");
        if !flags.quiet {
            println!("\n▶  Running scenario {label}");
        }

        let script_name = format!("{scenario_name}.sh");
        let script_path = test_dir.join(&script_name);
        if !script_path.is_file() {
            // Match official CLI behaviour: missing scenario script is a hard error.
            return Err(format!(
                "No scenario test script found at path '{}'. \
                 Either add a script to the test folder, or remove from scenarios.json.",
                script_path.display()
            )
            .into());
        }

        // Build config with the feature referencing local src.
        let base_image = scenario_config
            .get("image")
            .and_then(|v| v.as_str())
            .unwrap_or("ubuntu:focal");

        // Merge scenario config features with the local feature reference.
        let extra_features = build_scenario_features(scenario_config, feature_id);

        let workspace =
            build_test_workspace(project_folder, feature_id, base_image, &extra_features)?;

        let remote_user = scenario_config.get("remoteUser").and_then(|v| v.as_str());

        let container_id = bring_up_test_container(client, &workspace, remote_user).await?;

        let workspace_folder = format!("/workspaces/{}", workspace.dir_name);
        let test_result = inject_and_run_test(
            client,
            &container_id,
            project_folder,
            feature_id,
            &workspace_folder,
            &script_name,
            flags.quiet,
        )
        .await;

        // Always clean up this container unless explicitly preserved — even on error.
        if !flags.preserve_test_containers {
            let _ = client.remove_container(&container_id, false).await;
        }
        cleanup_workspace(&workspace)?;

        results.push(TestResult {
            label,
            passed: test_result?,
        });
    }

    Ok(results)
}

/// Run global scenarios from `test/_global/scenarios.json`.
async fn run_global_scenarios(
    client: &dyn cella_backend::ContainerBackend,
    project_folder: &Path,
    global_dir: &Path,
    filter: Option<&str>,
    flags: &RunFlags,
) -> Result<Vec<TestResult>, Box<dyn std::error::Error + Send + Sync>> {
    let scenarios_json = global_dir.join("scenarios.json");
    let raw = std::fs::read_to_string(&scenarios_json)
        .map_err(|e| format!("Cannot read {}: {e}", scenarios_json.display()))?;
    let scenarios = parse_scenarios(&raw)?;
    let filtered = filter_scenarios(&scenarios, filter);
    let mut results = Vec::new();

    for (scenario_name, scenario_config) in filtered {
        let label = format!("_global/{scenario_name}");
        if !flags.quiet {
            println!("\n▶  Running global scenario {label}");
        }

        let script_name = format!("{scenario_name}.sh");
        let script_path = global_dir.join(&script_name);
        if !script_path.is_file() {
            // Match official CLI behaviour: missing scenario script is a hard error.
            return Err(format!(
                "No scenario test script found at path '{}'. \
                 Either add a script to the test folder, or remove from scenarios.json.",
                script_path.display()
            )
            .into());
        }

        let base_image = scenario_config
            .get("image")
            .and_then(|v| v.as_str())
            .unwrap_or("ubuntu:focal");

        let workspace = build_global_test_workspace(project_folder, base_image, scenario_config)?;

        let remote_user = scenario_config.get("remoteUser").and_then(|v| v.as_str());

        let container_id = bring_up_test_container(client, &workspace, remote_user).await?;

        let workspace_folder = format!("/workspaces/{}", workspace.dir_name);
        let test_result = inject_and_run_global_test(
            client,
            &container_id,
            global_dir,
            &workspace_folder,
            &script_name,
            flags.quiet,
        )
        .await;

        // Always clean up this container unless explicitly preserved — even on error.
        if !flags.preserve_test_containers {
            let _ = client.remove_container(&container_id, false).await;
        }
        cleanup_workspace(&workspace)?;

        results.push(TestResult {
            label,
            passed: test_result?,
        });
    }

    Ok(results)
}

/// Temp workspace directory and supporting metadata.
struct TestWorkspace {
    dir: PathBuf,
    dir_name: String,
}

/// Build a temporary workspace for a feature's autogenerated or scenario test.
///
/// Writes a `.devcontainer/devcontainer.json` referencing the local feature
/// source, then copies the feature source directory into `.devcontainer/<id>/`.
fn build_test_workspace(
    project_folder: &Path,
    feature_id: &str,
    base_image: &str,
    extra_features: &[(String, Value)],
) -> Result<TestWorkspace, Box<dyn std::error::Error + Send + Sync>> {
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    let dir_name = format!("cella-feat-test-{timestamp}");
    let dir = std::env::temp_dir()
        .join("devcontainercli")
        .join("container-features-test")
        .join(&dir_name);
    let devcontainer_dir = dir.join(".devcontainer");
    std::fs::create_dir_all(&devcontainer_dir)?;

    // Build the features map for devcontainer.json.
    let local_ref = format!("./{feature_id}");
    let mut features_map = serde_json::Map::new();
    features_map.insert(local_ref, Value::Object(serde_json::Map::new()));
    for (k, v) in extra_features {
        features_map.insert(k.clone(), v.clone());
    }

    let config = serde_json::json!({
        "image": base_image,
        "features": features_map,
        "labels": {
            "devcontainer.is_test_run": "true"
        }
    });

    let config_path = devcontainer_dir.join("devcontainer.json");
    std::fs::write(&config_path, serde_json::to_string_pretty(&config)?)?;

    // Copy feature source into .devcontainer/<feature_id>/
    let src = project_folder.join("src").join(feature_id);
    let dst = devcontainer_dir.join(feature_id);
    copy_dir_all(&src, &dst)?;

    Ok(TestWorkspace { dir, dir_name })
}

/// Build a workspace for a global scenario test.
fn build_global_test_workspace(
    project_folder: &Path,
    base_image: &str,
    scenario_config: &Value,
) -> Result<TestWorkspace, Box<dyn std::error::Error + Send + Sync>> {
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    let dir_name = format!("cella-feat-test-global-{timestamp}");
    let dir = std::env::temp_dir()
        .join("devcontainercli")
        .join("container-features-test")
        .join(&dir_name);
    let devcontainer_dir = dir.join(".devcontainer");
    std::fs::create_dir_all(&devcontainer_dir)?;

    // The global scenario config IS the devcontainer.json content,
    // but we override the image and add our test label.
    let mut config = scenario_config.clone();
    if let Some(obj) = config.as_object_mut() {
        obj.insert("image".to_string(), Value::String(base_image.to_string()));
        obj.insert(
            "labels".to_string(),
            serde_json::json!({"devcontainer.is_test_run": "true"}),
        );
    }

    // Rewrite local feature references to point to copied sources.
    if let Some(features) = config
        .as_object_mut()
        .and_then(|o| o.get_mut("features"))
        .and_then(|f| f.as_object_mut())
    {
        let keys: Vec<String> = features.keys().cloned().collect();
        for key in keys {
            if let Some(feature_id) = key.strip_prefix("./") {
                let src = project_folder.join("src").join(feature_id);
                if src.is_dir() {
                    let dst = devcontainer_dir.join(feature_id);
                    copy_dir_all(&src, &dst)?;
                }
            }
        }
    }

    let config_path = devcontainer_dir.join("devcontainer.json");
    std::fs::write(&config_path, serde_json::to_string_pretty(&config)?)?;

    Ok(TestWorkspace { dir, dir_name })
}

/// Extract extra features from a scenario config, remapping local `./id`
/// references to the feature source relative path.
fn build_scenario_features(scenario_config: &Value, feature_id: &str) -> Vec<(String, Value)> {
    let Some(features) = scenario_config.get("features").and_then(|f| f.as_object()) else {
        // Default: use the feature itself with empty options.
        return vec![(
            format!("./{feature_id}"),
            Value::Object(serde_json::Map::new()),
        )];
    };
    features
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect()
}

/// Bring up a test container from a temp workspace using the up machinery.
async fn bring_up_test_container(
    client: &dyn cella_backend::ContainerBackend,
    workspace: &TestWorkspace,
    remote_user: Option<&str>,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    use cella_backend::FileToUpload;
    use cella_config::devcontainer::resolve;

    // Resolve the devcontainer config from the temp workspace.
    let resolved = resolve::config(&workspace.dir, None)?;

    // Build a minimal UpConfig. No daemon, no worktree, no lifecycle secrets.
    let container_name = cella_backend::container_name(&workspace.dir, Some("test"));
    let default_workspace_folder = format!("/workspaces/{}", workspace.dir_name);
    let empty_labels: HashMap<String, String> =
        std::iter::once(("devcontainer.is_test_run".to_string(), "true".to_string())).collect();
    let empty_vec: Vec<String> = Vec::new();
    let empty_mounts: Vec<cella_backend::MountConfig> = Vec::new();
    let up_config = cella_orchestrator::UpConfig {
        resolved: &resolved,
        container_name: &container_name,
        remote_env: &empty_vec,
        cli_remote_env: &empty_vec,
        workspace_folder_from_config: None,
        default_workspace_folder: &default_workspace_folder,
        extra_labels: &empty_labels,
        id_labels: &empty_vec,
        image_strategy: cella_orchestrator::ImageStrategy::Cached,
        remove_existing_container: false,
        skip_checksum: true,
        host_requirement_policy: cella_orchestrator::HostRequirementPolicy::Warn,
        network_rule_policy: cella_orchestrator::NetworkRulePolicy::Skip,
        pull_policy: None,
        build_secrets: Vec::new(),
        extra_networks: Vec::new(),
        mount_flags: cella_orchestrator::MountFlags {
            additional_cli_mounts: &empty_mounts,
            workspace_mount_consistency: None,
            mount_workspace_git_root: false,
            mount_git_worktree_common_dir: false,
        },
        lifecycle_secrets: &empty_vec,
        user_env_probe: cella_env::user_env_probe::UserEnvProbe::LoginInteractiveShell,
        lifecycle_gate: cella_backend::LifecycleGate::default(),
        expect_existing_container: false,
        build_tuning: cella_orchestrator::BuildTuning::default(),
        gpu_availability: cella_backend::GpuAvailability::Detect,
        update_remote_user_uid_default: cella_backend::UpdateRemoteUserUidDefault::On,
        metadata_options: cella_orchestrator::MetadataOptions::default(),
        dotfiles: cella_orchestrator::config::DotfilesConfig::default(),
    };

    let hooks = NullUpHooks;
    // Create a progress sender that discards all events — test containers
    // don't need spinner output wired to a CLI progress renderer.
    let (tx, mut rx) = tokio::sync::mpsc::channel::<cella_orchestrator::ProgressEvent>(256);
    let sink = tokio::spawn(async move { while rx.recv().await.is_some() {} });
    let sender = cella_orchestrator::ProgressSender::new(tx, false);
    let result = cella_orchestrator::up::ensure_up(client, &up_config, &hooks, sender).await;
    let _ = sink.await;
    let result = result.map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;

    // Apply remoteUser override if given.
    if let Some(user) = remote_user {
        let _ = client
            .exec_command(
                &result.container_id,
                &cella_backend::ExecOptions {
                    cmd: vec![
                        "sh".into(),
                        "-c".into(),
                        format!("id -u {user} > /dev/null 2>&1 || useradd -m {user}"),
                    ],
                    user: Some("root".to_string()),
                    env: None,
                    working_dir: None,
                },
            )
            .await;
    }

    // Upload test-lib to a known scratch location so inject_and_run_test can
    // copy it into the workspace folder later.
    let lib_bytes = TEST_LIB_CONTENT.as_bytes().to_vec();
    client
        .upload_files(
            &result.container_id,
            &[FileToUpload {
                path: "/tmp/dev-container-features-test-lib".to_string(),
                content: lib_bytes,
                mode: 0o755,
            }],
        )
        .await
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;

    Ok(result.container_id)
}

/// Copy the test directory and test-lib into the workspace folder, then run the
/// named script, returning `true` if it exits with code 0.
async fn inject_and_run_test(
    client: &dyn cella_backend::ContainerBackend,
    container_id: &str,
    project_folder: &Path,
    feature_id: &str,
    workspace_folder: &str,
    script_name: &str,
    quiet: bool,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    use cella_backend::ExecOptions;

    let test_dir = project_folder.join("test").join(feature_id);

    // Upload every file from test/<feature_id>/ into the workspace folder.
    upload_dir(client, container_id, &test_dir, workspace_folder).await?;

    // Copy test-lib from /tmp scratch to workspace folder.
    copy_test_lib(client, container_id, workspace_folder).await?;

    // chmod -R 777 on the workspace folder.
    let _ = client
        .exec_command(
            container_id,
            &ExecOptions {
                cmd: vec![
                    "chmod".into(),
                    "-R".into(),
                    "777".into(),
                    workspace_folder.to_string(),
                ],
                user: Some("root".to_string()),
                env: None,
                working_dir: None,
            },
        )
        .await;

    // Execute the test script.
    run_test_script(client, container_id, workspace_folder, script_name, quiet).await
}

/// Variant of `inject_and_run_test` for global scenarios (test dir is the global dir).
async fn inject_and_run_global_test(
    client: &dyn cella_backend::ContainerBackend,
    container_id: &str,
    global_dir: &Path,
    workspace_folder: &str,
    script_name: &str,
    quiet: bool,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    use cella_backend::ExecOptions;

    upload_dir(client, container_id, global_dir, workspace_folder).await?;
    copy_test_lib(client, container_id, workspace_folder).await?;

    let _ = client
        .exec_command(
            container_id,
            &ExecOptions {
                cmd: vec![
                    "chmod".into(),
                    "-R".into(),
                    "777".into(),
                    workspace_folder.to_string(),
                ],
                user: Some("root".to_string()),
                env: None,
                working_dir: None,
            },
        )
        .await;

    run_test_script(client, container_id, workspace_folder, script_name, quiet).await
}

/// Copy the test-lib from `/tmp` scratch into the workspace folder.
async fn copy_test_lib(
    client: &dyn cella_backend::ContainerBackend,
    container_id: &str,
    workspace_folder: &str,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use cella_backend::ExecOptions;

    client
        .exec_command(
            container_id,
            &ExecOptions {
                cmd: vec![
                    "cp".into(),
                    "/tmp/dev-container-features-test-lib".into(),
                    format!("{workspace_folder}/dev-container-features-test-lib"),
                ],
                user: Some("root".to_string()),
                env: None,
                working_dir: None,
            },
        )
        .await
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;

    Ok(())
}

/// Run a test script inside the container, streaming output to stdout/stderr.
async fn run_test_script(
    client: &dyn cella_backend::ContainerBackend,
    container_id: &str,
    workspace_folder: &str,
    script_name: &str,
    quiet: bool,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    use cella_backend::ExecOptions;

    let script_path = format!("{workspace_folder}/{script_name}");

    if quiet {
        let result = client
            .exec_command(
                container_id,
                &ExecOptions {
                    cmd: vec!["bash".into(), script_path],
                    user: Some("root".to_string()),
                    env: None,
                    working_dir: Some(workspace_folder.to_string()),
                },
            )
            .await
            .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;
        Ok(result.exit_code == 0)
    } else {
        let stdout_writer: Box<dyn std::io::Write + Send> = Box::new(std::io::stdout());
        let stderr_writer: Box<dyn std::io::Write + Send> = Box::new(std::io::stderr());
        let result = client
            .exec_stream(
                container_id,
                &ExecOptions {
                    cmd: vec!["bash".into(), script_path],
                    user: Some("root".to_string()),
                    env: None,
                    working_dir: Some(workspace_folder.to_string()),
                },
                stdout_writer,
                stderr_writer,
            )
            .await
            .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;
        Ok(result.exit_code == 0)
    }
}

/// Upload all files from a host directory into a container path.
async fn upload_dir(
    client: &dyn cella_backend::ContainerBackend,
    container_id: &str,
    src_dir: &Path,
    container_dest: &str,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let mut files = Vec::new();
    collect_files(src_dir, src_dir, container_dest, &mut files)?;
    if !files.is_empty() {
        client
            .upload_files(container_id, &files)
            .await
            .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;
    }
    Ok(())
}

/// Recursively collect files from `dir`, building `FileToUpload` entries with
/// paths relative to `base` appended to `container_dest`.
fn collect_files(
    dir: &Path,
    base: &Path,
    container_dest: &str,
    out: &mut Vec<cella_backend::FileToUpload>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, base, container_dest, out)?;
        } else {
            let rel = path.strip_prefix(base).unwrap_or(&path);
            let container_path = format!(
                "{container_dest}/{}",
                rel.to_string_lossy().replace('\\', "/")
            );
            let content = std::fs::read(&path)?;
            // Mark shell scripts executable; everything else is read-only.
            let mode = if path
                .extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| e.eq_ignore_ascii_case("sh"))
            {
                0o755
            } else {
                0o644
            };
            out.push(cella_backend::FileToUpload {
                path: container_path,
                content,
                mode,
            });
        }
    }
    Ok(())
}

/// Recursively copy a directory tree on the host.
fn copy_dir_all(src: &Path, dst: &Path) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        if ty.is_dir() {
            copy_dir_all(&entry.path(), &dst.join(entry.file_name()))?;
        } else {
            std::fs::copy(entry.path(), dst.join(entry.file_name()))?;
        }
    }
    Ok(())
}

/// Remove the temp workspace directory.
fn cleanup_workspace(
    workspace: &TestWorkspace,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    if workspace.dir.exists() {
        std::fs::remove_dir_all(&workspace.dir)?;
    }
    Ok(())
}

/// Remove all containers labelled `devcontainer.is_test_run=true`.
async fn cleanup_test_containers(client: &dyn cella_backend::ContainerBackend) {
    let Ok(containers) = client.list_cella_containers(false).await else {
        return;
    };
    for c in containers {
        if c.labels
            .get("devcontainer.is_test_run")
            .is_some_and(|v| v == "true")
        {
            let _ = client.remove_container(&c.id, false).await;
        }
    }
}

/// Print a summary table with ✅/❌ per test.
fn print_results_table(
    feature_results: &[FeatureResults],
    global_results: &[TestResult],
    quiet: bool,
) {
    if quiet {
        return;
    }
    println!("\n── Test Results ─────────────────────────────────────────────");
    for fr in feature_results {
        for r in &fr.results {
            let icon = if r.passed { "✅" } else { "❌" };
            println!("  {icon}  {}", r.label);
        }
    }
    for r in global_results {
        let icon = if r.passed { "✅" } else { "❌" };
        println!("  {icon}  {}", r.label);
    }
    println!("────────────────────────────────────────────────────────────");
}

/// No-op implementation of `UpHooks` for test container creation.
/// Feature tests don't need daemon registration or ssh-agent bridging.
struct NullUpHooks;

impl cella_orchestrator::up::UpHooks for NullUpHooks {
    fn daemon_env<'a>(
        &'a self,
        _container_name: &'a str,
        _host_gateway: &'a str,
    ) -> Pin<Box<dyn Future<Output = Vec<String>> + Send + 'a>> {
        Box::pin(async { Vec::new() })
    }

    fn sync_agent_runtime<'a>(
        &'a self,
        _client: &'a dyn cella_backend::ContainerBackend,
    ) -> Pin<Box<dyn Future<Output = ()> + Send + 'a>> {
        Box::pin(async {})
    }

    fn on_container_started(
        &self,
        _container_id: &str,
        _container_name: &str,
        _container_ip: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = ()> + Send + '_>> {
        Box::pin(async {})
    }

    fn update_container_ip(
        &self,
        _container_id: &str,
        _container_ip: Option<&str>,
    ) -> Pin<Box<dyn Future<Output = bool> + Send + '_>> {
        Box::pin(async { false })
    }

    fn on_container_stopping(
        &self,
        _container_name: &str,
    ) -> Pin<Box<dyn Future<Output = ()> + Send + '_>> {
        Box::pin(async {})
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use cella_backend::{
        BackendCapabilities, BackendError, BackendKind, BoxFuture, ContainerBackend,
    };

    use super::*;

    // ---------------------------------------------------------------------------
    // Minimal panic-on-call backend for tests that must never reach container ops
    // ---------------------------------------------------------------------------

    struct NeverCalledBackend;

    impl ContainerBackend for NeverCalledBackend {
        fn kind(&self) -> BackendKind {
            BackendKind::Docker
        }

        fn capabilities(&self) -> BackendCapabilities {
            BackendCapabilities {
                compose: false,
                managed_agent: false,
            }
        }

        fn find_container<'a>(
            &'a self,
            _: &'a Path,
        ) -> BoxFuture<'a, Result<Option<cella_backend::ContainerInfo>, BackendError>> {
            panic!("unexpected find_container call");
        }

        fn create_container<'a>(
            &'a self,
            _: &'a cella_backend::CreateContainerOptions,
        ) -> BoxFuture<'a, Result<String, BackendError>> {
            panic!("unexpected create_container call");
        }

        fn start_container<'a>(&'a self, _: &'a str) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected start_container call");
        }

        fn stop_container<'a>(&'a self, _: &'a str) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected stop_container call");
        }

        fn remove_container<'a>(
            &'a self,
            _: &'a str,
            _: bool,
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected remove_container call");
        }

        fn inspect_container<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<cella_backend::ContainerInfo, BackendError>> {
            panic!("unexpected inspect_container call");
        }

        fn list_cella_containers(
            &self,
            _: bool,
        ) -> BoxFuture<'_, Result<Vec<cella_backend::ContainerInfo>, BackendError>> {
            panic!("unexpected list_cella_containers call");
        }

        fn find_compose_service<'a>(
            &'a self,
            _: &'a str,
            _: &'a str,
        ) -> BoxFuture<'a, Result<Option<cella_backend::ContainerInfo>, BackendError>> {
            panic!("unexpected find_compose_service call");
        }

        fn find_container_by_label<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<Option<cella_backend::ContainerInfo>, BackendError>> {
            panic!("unexpected find_container_by_label call");
        }

        fn container_logs<'a>(
            &'a self,
            _: &'a str,
            _: u32,
        ) -> BoxFuture<'a, Result<String, BackendError>> {
            panic!("unexpected container_logs call");
        }

        fn exec_command<'a>(
            &'a self,
            _: &'a str,
            _: &'a cella_backend::ExecOptions,
        ) -> BoxFuture<'a, Result<cella_backend::ExecResult, BackendError>> {
            panic!("unexpected exec_command call");
        }

        fn exec_stream<'a>(
            &'a self,
            _: &'a str,
            _: &'a cella_backend::ExecOptions,
            _: Box<dyn std::io::Write + Send + 'a>,
            _: Box<dyn std::io::Write + Send + 'a>,
        ) -> BoxFuture<'a, Result<cella_backend::ExecResult, BackendError>> {
            panic!("unexpected exec_stream call");
        }

        fn exec_interactive<'a>(
            &'a self,
            _: &'a str,
            _: &'a cella_backend::InteractiveExecOptions,
        ) -> BoxFuture<'a, Result<i64, BackendError>> {
            panic!("unexpected exec_interactive call");
        }

        fn exec_detached<'a>(
            &'a self,
            _: &'a str,
            _: &'a cella_backend::ExecOptions,
        ) -> BoxFuture<'a, Result<String, BackendError>> {
            panic!("unexpected exec_detached call");
        }

        fn pull_image<'a>(&'a self, _: &'a str) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected pull_image call");
        }

        fn build_image<'a>(
            &'a self,
            _: &'a cella_backend::BuildOptions,
        ) -> BoxFuture<'a, Result<String, BackendError>> {
            panic!("unexpected build_image call");
        }

        fn image_exists<'a>(&'a self, _: &'a str) -> BoxFuture<'a, Result<bool, BackendError>> {
            panic!("unexpected image_exists call");
        }

        fn inspect_image_details<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<cella_backend::ImageDetails, BackendError>> {
            panic!("unexpected inspect_image_details call");
        }

        fn upload_files<'a>(
            &'a self,
            _: &'a str,
            _: &'a [cella_backend::FileToUpload],
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected upload_files call");
        }

        fn ping(&self) -> BoxFuture<'_, Result<(), BackendError>> {
            panic!("unexpected ping call");
        }

        fn host_gateway(&self) -> &'static str {
            "host.docker.internal"
        }

        fn detect_platform(&self) -> BoxFuture<'_, Result<cella_backend::Platform, BackendError>> {
            panic!("unexpected detect_platform call");
        }

        fn detect_container_arch(&self) -> BoxFuture<'_, Result<String, BackendError>> {
            panic!("unexpected detect_container_arch call");
        }

        fn inspect_image_env<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<Vec<String>, BackendError>> {
            panic!("unexpected inspect_image_env call");
        }

        fn inspect_image_user<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<String, BackendError>> {
            panic!("unexpected inspect_image_user call");
        }

        fn ensure_network(&self) -> BoxFuture<'_, Result<(), BackendError>> {
            panic!("unexpected ensure_network call");
        }

        fn ensure_container_network<'a>(
            &'a self,
            _: &'a str,
            _: &'a Path,
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected ensure_container_network call");
        }

        fn get_container_ip<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<Option<String>, BackendError>> {
            panic!("unexpected get_container_ip call");
        }

        fn ensure_agent_provisioned<'a>(
            &'a self,
            _: &'a str,
            _: &'a str,
            _: bool,
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected ensure_agent_provisioned call");
        }

        fn write_agent_addr<'a>(
            &'a self,
            _: &'a str,
            _: &'a str,
            _: &'a str,
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected write_agent_addr call");
        }

        fn agent_volume_mount(&self) -> (String, String, bool) {
            panic!("unexpected agent_volume_mount call");
        }

        fn prune_old_agent_versions<'a>(
            &'a self,
            _: &'a str,
        ) -> BoxFuture<'a, Result<(), BackendError>> {
            panic!("unexpected prune_old_agent_versions call");
        }
    }

    #[test]
    fn parse_scenarios_empty_object() {
        let result = parse_scenarios("{}").unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn parse_scenarios_valid() {
        let json =
            r#"{"scenario_a": {"image": "ubuntu:22.04"}, "scenario_b": {"image": "debian:11"}}"#;
        let result = parse_scenarios(json).unwrap();
        assert_eq!(result.len(), 2);
        assert!(result.contains_key("scenario_a"));
        assert!(result.contains_key("scenario_b"));
        assert_eq!(
            result["scenario_a"].get("image").and_then(|v| v.as_str()),
            Some("ubuntu:22.04")
        );
    }

    #[test]
    fn parse_scenarios_invalid_json() {
        let result = parse_scenarios("not valid json");
        assert!(result.is_err());
    }

    #[test]
    fn filter_scenarios_by_name() {
        let mut scenarios = HashMap::new();
        scenarios.insert("install_default".to_string(), serde_json::json!({}));
        scenarios.insert("install_with_options".to_string(), serde_json::json!({}));
        scenarios.insert("verify_only".to_string(), serde_json::json!({}));

        // "install_" only matches the two install_* scenarios, not verify_only.
        let filtered = filter_scenarios(&scenarios, Some("install_"));
        assert_eq!(filtered.len(), 2);
        let names: Vec<&str> = filtered.iter().map(|(n, _)| *n).collect();
        assert!(names.contains(&"install_default"));
        assert!(names.contains(&"install_with_options"));
        assert!(!names.contains(&"verify_only"));
    }

    #[test]
    fn test_result_all_passed() {
        let results = [
            TestResult {
                label: "a".to_string(),
                passed: true,
            },
            TestResult {
                label: "b".to_string(),
                passed: true,
            },
        ];
        assert!(results.iter().all(|r| r.passed));
    }

    #[test]
    fn test_result_any_failed() {
        let results = [
            TestResult {
                label: "a".to_string(),
                passed: true,
            },
            TestResult {
                label: "b".to_string(),
                passed: false,
            },
        ];
        assert!(!results.iter().all(|r| r.passed));
    }

    // ---------------------------------------------------------------------------
    // echoStderr content assertion
    // ---------------------------------------------------------------------------

    /// The embedded test-lib must NOT call `echoStderr -e "..."` because `echo`
    /// treats `-e` as a literal argument when called via `echo "$@"` on some
    /// systems. The corrected form omits the flag — the message is plain text.
    #[test]
    fn test_lib_echostderr_no_minus_e_flag() {
        // The old (buggy) line started with `echoStderr -e`.  After the fix the
        // `reportResults` block must print via plain `echoStderr "..."`.
        assert!(
            !TEST_LIB_CONTENT.contains(r#"echoStderr -e "💥"#),
            "TEST_LIB_CONTENT still contains the buggy `echoStderr -e` call"
        );
        // The corrected line is present.
        assert!(
            TEST_LIB_CONTENT.contains(r#"echoStderr "💥  Failed tests:"#),
            "TEST_LIB_CONTENT is missing the corrected echoStderr call"
        );
    }

    // ---------------------------------------------------------------------------
    // Missing scenario script → hard error
    // ---------------------------------------------------------------------------

    /// `run_scenarios` must return `Err` (not a passing/failing `TestResult`) when
    /// a scenario listed in `scenarios.json` has no corresponding `.sh` file.
    /// This matches the official devcontainer CLI's `fail()` behaviour.
    #[tokio::test]
    async fn run_scenarios_missing_script_is_error() {
        let tmp = tempfile::tempdir().unwrap();
        // A project folder with the minimum directory structure.
        let project_folder = tmp.path().join("project");
        let feature_id = "myfeature";
        let test_dir = project_folder.join("test").join(feature_id);
        std::fs::create_dir_all(&test_dir).unwrap();
        std::fs::create_dir_all(project_folder.join("src").join(feature_id)).unwrap();

        let mut scenarios = HashMap::new();
        // "no_script" is in scenarios.json but there is no `no_script.sh`.
        scenarios.insert("no_script".to_string(), serde_json::json!({}));

        let backend = NeverCalledBackend;
        let flags = RunFlags {
            quiet: true,
            preserve_test_containers: false,
        };
        let result = run_scenarios(
            &backend,
            &project_folder,
            feature_id,
            &scenarios,
            &test_dir,
            None,
            &flags,
        )
        .await;

        assert!(result.is_err(), "expected Err for missing scenario script");
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("no_script.sh"),
            "error message should name the missing file; got: {msg}"
        );
    }

    /// `run_global_scenarios` must return `Err` when a scenario listed in the
    /// global `scenarios.json` has no matching `.sh` file.
    #[tokio::test]
    async fn run_global_scenarios_missing_script_is_error() {
        let tmp = tempfile::tempdir().unwrap();
        let project_folder = tmp.path().join("project");
        let global_dir = tmp.path().join("_global");
        std::fs::create_dir_all(&global_dir).unwrap();
        std::fs::create_dir_all(project_folder.join("src")).unwrap();

        // Write a scenarios.json that names a scenario whose .sh is absent.
        let scenarios_json = global_dir.join("scenarios.json");
        std::fs::write(
            &scenarios_json,
            r#"{"missing_global": {"image": "ubuntu:focal"}}"#,
        )
        .unwrap();

        let backend = NeverCalledBackend;
        let flags = RunFlags {
            quiet: true,
            preserve_test_containers: false,
        };
        let result =
            run_global_scenarios(&backend, &project_folder, &global_dir, None, &flags).await;

        assert!(
            result.is_err(),
            "expected Err for missing global scenario script"
        );
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("missing_global.sh"),
            "error message should name the missing file; got: {msg}"
        );
    }

    // ---------------------------------------------------------------------------
    // preserve_test_containers flag wiring
    // ---------------------------------------------------------------------------

    /// When `preserve_test_containers` is `true` the scenario-missing error path
    /// still propagates before any container is started — the backend is never
    /// called and the error message is the same.
    #[tokio::test]
    async fn run_scenarios_missing_script_error_with_preserve() {
        let tmp = tempfile::tempdir().unwrap();
        let project_folder = tmp.path().join("project");
        let feature_id = "feat";
        let test_dir = project_folder.join("test").join(feature_id);
        std::fs::create_dir_all(&test_dir).unwrap();
        std::fs::create_dir_all(project_folder.join("src").join(feature_id)).unwrap();

        let mut scenarios = HashMap::new();
        scenarios.insert("ghost".to_string(), serde_json::json!({}));

        let backend = NeverCalledBackend;
        let flags = RunFlags {
            quiet: true,
            preserve_test_containers: true, // preserve = true: error still propagates
        };
        let result = run_scenarios(
            &backend,
            &project_folder,
            feature_id,
            &scenarios,
            &test_dir,
            None,
            &flags,
        )
        .await;

        assert!(result.is_err());
    }
}
