//! Generate the cella override Docker Compose YAML file.
//!
//! The override file is passed as the last `-f` flag to `docker compose`,
//! allowing cella to inject its customizations into the primary service:
//! image swap (for features), agent volume, environment variables, and labels.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::{Path, PathBuf};

use cella_backend::MountSpec;

use crate::error::CellaComposeError;

/// A `BuildKit` secret to forward to compose builds.
#[derive(Debug, Clone)]
pub struct ComposeSecret {
    /// Secret identifier (matches `--mount=type=secret,id=<id>` in Dockerfile).
    pub id: String,
    /// Host file path containing the secret value.
    pub file: Option<PathBuf>,
    /// Environment variable containing the secret value.
    pub environment: Option<String>,
}

/// Configuration for generating the override compose file.
pub struct OverrideConfig {
    /// The primary service name (must match a service in the user's compose file).
    pub primary_service: String,
    /// Feature-enriched image tag (if features were built).
    pub image_override: Option<String>,
    /// Whether to override the service's CMD/ENTRYPOINT (defaults to false for compose).
    pub override_command: bool,
    /// Agent volume name (e.g., `cella-agent`).
    pub agent_volume_name: String,
    /// Agent volume mount target inside the container (e.g., `/cella`).
    pub agent_volume_target: String,
    /// Extra environment variables to inject (`KEY=VALUE` format).
    pub extra_env: Vec<String>,
    /// Extra labels for the primary service container.
    pub extra_labels: BTreeMap<String, String>,
    /// Override `build.dockerfile` for combined Dockerfile (compose + features).
    pub build_dockerfile: Option<PathBuf>,
    /// Override `build.target` for the features target stage.
    pub build_target: Option<String>,
    /// Override `build.context` for image-only services that need a synthetic build.
    pub build_context: Option<PathBuf>,
    /// Named build contexts for Docker `BuildKit` (e.g., feature content source).
    ///
    /// Emitted as `build.additional_contexts` in the compose override YAML.
    /// Requires Docker Compose >= 2.17.0.
    pub additional_contexts: BTreeMap<String, PathBuf>,
    /// `BuildKit` secrets forwarded to compose builds via the override YAML.
    pub build_secrets: Vec<ComposeSecret>,
    /// Extra volume mounts (long-form YAML) appended to the primary service's
    /// `volumes:` list after the agent volume.
    pub extra_volumes: Vec<MountSpec>,
}

/// Generate the override compose YAML as a string.
///
/// The output is a valid Docker Compose file that overrides the primary service
/// with cella-specific configuration. It is designed to be passed as the last
/// `-f` flag so its values take precedence.
pub fn generate_override_yaml(config: &OverrideConfig) -> String {
    let mut yaml = String::from("# Auto-generated by cella. Do not edit.\n");

    // Services section
    yaml.push_str("services:\n");
    let _ = writeln!(yaml, "  {}:", config.primary_service);

    // Image override (for image-only services with features, to avoid retagging original)
    if let Some(ref image) = config.image_override {
        let _ = writeln!(yaml, "    image: \"{image}\"");
    }

    // Build override (combined Dockerfile for compose + features)
    let has_build_section = config.build_dockerfile.is_some() || !config.build_secrets.is_empty();
    if has_build_section {
        yaml.push_str("    build:\n");
        if let Some(ref dockerfile) = config.build_dockerfile {
            let _ = writeln!(yaml, "      dockerfile: \"{}\"", dockerfile.display());
            if let Some(ref target) = config.build_target {
                let _ = writeln!(yaml, "      target: \"{target}\"");
            }
            if let Some(ref context) = config.build_context {
                let _ = writeln!(yaml, "      context: \"{}\"", context.display());
            }
            if !config.additional_contexts.is_empty() {
                yaml.push_str("      additional_contexts:\n");
                for (name, path) in &config.additional_contexts {
                    let _ = writeln!(yaml, "        - {name}={}", path.display());
                }
            }
        }
        if !config.build_secrets.is_empty() {
            yaml.push_str("      secrets:\n");
            for secret in &config.build_secrets {
                let _ = writeln!(yaml, "        - {}", secret.id);
            }
        }
    }

    // Command override (only if explicitly enabled; compose default is false)
    if config.override_command {
        yaml.push_str("    entrypoint: [\"/bin/sh\", \"-c\"]\n");
        yaml.push_str("    command: [\"while sleep 1000; do :; done\"]\n");
    }

    // Environment variables
    if !config.extra_env.is_empty() {
        yaml.push_str("    environment:\n");
        for env in &config.extra_env {
            let _ = writeln!(yaml, "      - \"{env}\"");
        }
    }

    // Labels
    if !config.extra_labels.is_empty() {
        yaml.push_str("    labels:\n");
        for (k, v) in &config.extra_labels {
            let _ = writeln!(yaml, "      {k}: \"{v}\"");
        }
    }

    // Agent volume mount (read-only)
    yaml.push_str("    volumes:\n");
    let _ = writeln!(
        yaml,
        "      - {}:{}:ro",
        config.agent_volume_name, config.agent_volume_target
    );

    // Extra volume mounts (long-form YAML entries)
    for spec in &config.extra_volumes {
        yaml.push_str(&spec.to_compose_yaml_entry("      "));
    }

    // Top-level secrets declarations (file/environment sources)
    if !config.build_secrets.is_empty() {
        yaml.push_str("secrets:\n");
        for secret in &config.build_secrets {
            let _ = writeln!(yaml, "  {}:", secret.id);
            if let Some(ref file) = secret.file {
                let _ = writeln!(yaml, "    file: \"{}\"", file.display());
            }
            if let Some(ref env) = secret.environment {
                let _ = writeln!(yaml, "    environment: \"{env}\"");
            }
        }
    }

    // Top-level volumes declaration (external volume)
    yaml.push_str("volumes:\n");
    let _ = writeln!(yaml, "  {}:", config.agent_volume_name);
    yaml.push_str("    external: true\n");

    yaml
}

/// Write the override file to disk, creating parent directories as needed.
///
/// # Errors
///
/// Returns an error if the parent directories cannot be created or if writing
/// the file fails.
pub fn write_override_file(path: &Path, content: &str) -> Result<(), CellaComposeError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

/// Remove the override file and its parent directory if empty.
pub fn cleanup_override_file(path: &Path) {
    let _ = std::fs::remove_file(path);
    if let Some(parent) = path.parent() {
        let _ = std::fs::remove_dir(parent);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_config() -> OverrideConfig {
        OverrideConfig {
            primary_service: "app".to_string(),
            image_override: None,
            override_command: false,
            agent_volume_name: "cella-agent".to_string(),
            agent_volume_target: "/cella".to_string(),
            extra_env: Vec::new(),
            extra_labels: BTreeMap::new(),
            build_dockerfile: None,
            build_target: None,
            build_context: None,
            additional_contexts: BTreeMap::new(),
            build_secrets: Vec::new(),
            extra_volumes: Vec::new(),
        }
    }

    #[test]
    fn minimal_override() {
        let config = base_config();
        let yaml = generate_override_yaml(&config);
        insta::assert_snapshot!(yaml, @"
        # Auto-generated by cella. Do not edit.
        services:
          app:
            volumes:
              - cella-agent:/cella:ro
        volumes:
          cella-agent:
            external: true
        ");
    }

    #[test]
    fn with_image_override() {
        let mut config = base_config();
        config.image_override = Some("cella-img-myapp-abc12345-def67890".to_string());
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("image: \"cella-img-myapp-abc12345-def67890\""));
    }

    #[test]
    fn with_command_override() {
        let mut config = base_config();
        config.override_command = true;
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("entrypoint:"));
        assert!(yaml.contains("command:"));
    }

    #[test]
    fn without_command_override() {
        let config = base_config();
        let yaml = generate_override_yaml(&config);
        assert!(!yaml.contains("entrypoint:"));
        assert!(!yaml.contains("command:"));
    }

    #[test]
    fn with_env_vars() {
        let mut config = base_config();
        config.extra_env = vec![
            "CELLA_DAEMON_PORT=9876".to_string(),
            "CELLA_AUTH_TOKEN=abc123".to_string(),
        ];
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("environment:"));
        assert!(yaml.contains("CELLA_DAEMON_PORT=9876"));
        assert!(yaml.contains("CELLA_AUTH_TOKEN=abc123"));
    }

    #[test]
    fn with_labels() {
        let mut config = base_config();
        config
            .extra_labels
            .insert("dev.cella.tool".to_string(), "cella".to_string());
        config.extra_labels.insert(
            "dev.cella.compose_project".to_string(),
            "myproject".to_string(),
        );
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("labels:"));
        assert!(yaml.contains("dev.cella.tool: \"cella\""));
        assert!(yaml.contains("dev.cella.compose_project: \"myproject\""));
    }

    #[test]
    fn full_override() {
        let mut config = base_config();
        config.image_override = Some("cella-img-app-12345678".to_string());
        config.override_command = true;
        config.extra_env = vec!["CELLA_DAEMON_PORT=9876".to_string()];
        config
            .extra_labels
            .insert("dev.cella.tool".to_string(), "cella".to_string());
        let yaml = generate_override_yaml(&config);
        insta::assert_snapshot!(yaml, @r#"
        # Auto-generated by cella. Do not edit.
        services:
          app:
            image: "cella-img-app-12345678"
            entrypoint: ["/bin/sh", "-c"]
            command: ["while sleep 1000; do :; done"]
            environment:
              - "CELLA_DAEMON_PORT=9876"
            labels:
              dev.cella.tool: "cella"
            volumes:
              - cella-agent:/cella:ro
        volumes:
          cella-agent:
            external: true
        "#);
    }

    #[test]
    fn with_build_override() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from(
            "/home/user/.cella/compose/proj/Dockerfile.combined",
        ));
        config.build_target = Some("dev_containers_target_stage".to_string());
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("build:"));
        assert!(yaml.contains("dockerfile:"));
        assert!(yaml.contains("Dockerfile.combined"));
        assert!(yaml.contains("target: \"dev_containers_target_stage\""));
        // No context override for build-based services
        assert!(!yaml.contains("context:"));
    }

    #[test]
    fn with_build_override_and_context() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from("/tmp/Dockerfile.combined"));
        config.build_target = Some("dev_containers_target_stage".to_string());
        config.build_context = Some(PathBuf::from("/tmp/features-context"));
        config.image_override = Some("cella-img-app-features".to_string());
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("image: \"cella-img-app-features\""));
        assert!(yaml.contains("build:"));
        assert!(yaml.contains("dockerfile:"));
        assert!(yaml.contains("target:"));
        assert!(yaml.contains("context: \"/tmp/features-context\""));
    }

    #[test]
    fn with_additional_contexts() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from("/tmp/Dockerfile.combined"));
        config.build_target = Some("dev_containers_target_stage".to_string());
        config.additional_contexts.insert(
            "dev_containers_feature_content_source".to_string(),
            PathBuf::from("/home/user/.cache/cella/features/builds/abc123"),
        );
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("additional_contexts:"));
        assert!(yaml.contains(
            "dev_containers_feature_content_source=/home/user/.cache/cella/features/builds/abc123"
        ));
    }

    #[test]
    fn with_build_override_context_and_additional_contexts() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from("/tmp/Dockerfile.combined"));
        config.build_target = Some("dev_containers_target_stage".to_string());
        config.build_context = Some(PathBuf::from("/tmp/empty-context"));
        config.image_override = Some("cella-img-app-features".to_string());
        config.additional_contexts.insert(
            "dev_containers_feature_content_source".to_string(),
            PathBuf::from("/tmp/features-context"),
        );
        let yaml = generate_override_yaml(&config);
        insta::assert_snapshot!(yaml, @r#"
        # Auto-generated by cella. Do not edit.
        services:
          app:
            image: "cella-img-app-features"
            build:
              dockerfile: "/tmp/Dockerfile.combined"
              target: "dev_containers_target_stage"
              context: "/tmp/empty-context"
              additional_contexts:
                - dev_containers_feature_content_source=/tmp/features-context
            volumes:
              - cella-agent:/cella:ro
        volumes:
          cella-agent:
            external: true
        "#);
    }

    #[test]
    fn write_and_cleanup() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("project").join("docker-compose.cella.yml");

        write_override_file(&path, "test content").unwrap();
        assert!(path.exists());

        cleanup_override_file(&path);
        assert!(!path.exists());
    }

    #[test]
    fn additional_contexts_without_build_dockerfile_are_ignored() {
        let mut config = base_config();
        // Set additional_contexts but NOT build_dockerfile
        config
            .additional_contexts
            .insert("feature_src".to_string(), PathBuf::from("/tmp/features"));
        let yaml = generate_override_yaml(&config);
        // additional_contexts should NOT appear since build_dockerfile is None
        assert!(
            !yaml.contains("additional_contexts"),
            "additional_contexts should be omitted when build_dockerfile is None"
        );
    }

    #[test]
    fn multiple_additional_contexts_sorted() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from("/tmp/Dockerfile.combined"));
        config
            .additional_contexts
            .insert("zulu_context".to_string(), PathBuf::from("/tmp/zulu"));
        config
            .additional_contexts
            .insert("alpha_context".to_string(), PathBuf::from("/tmp/alpha"));
        config
            .additional_contexts
            .insert("mike_context".to_string(), PathBuf::from("/tmp/mike"));
        let yaml = generate_override_yaml(&config);
        // BTreeMap guarantees sorted order
        let alpha_pos = yaml.find("alpha_context").expect("alpha_context not found");
        let mike_pos = yaml.find("mike_context").expect("mike_context not found");
        let zulu_pos = yaml.find("zulu_context").expect("zulu_context not found");
        assert!(
            alpha_pos < mike_pos && mike_pos < zulu_pos,
            "additional_contexts should appear in BTreeMap (alphabetical) order"
        );
    }

    #[test]
    fn special_characters_in_paths_are_quoted() {
        let mut config = base_config();
        config.build_dockerfile = Some(PathBuf::from("/tmp/my project/Dockerfile"));
        config.build_target = Some("dev_stage".to_string());
        let yaml = generate_override_yaml(&config);
        // The path with spaces should appear in the YAML
        assert!(yaml.contains("my project"));
        // The dockerfile value should be quoted
        assert!(yaml.contains(r#"dockerfile: "/tmp/my project/Dockerfile""#));
    }

    #[test]
    fn with_single_bind_mount() {
        let mut config = base_config();
        config.extra_volumes = vec![MountSpec::bind("/home/u/.claude", "/root/.claude")];
        let yaml = generate_override_yaml(&config);
        insta::assert_snapshot!(yaml, @r#"
        # Auto-generated by cella. Do not edit.
        services:
          app:
            volumes:
              - cella-agent:/cella:ro
              - type: bind
                source: "/home/u/.claude"
                target: "/root/.claude"
        volumes:
          cella-agent:
            external: true
        "#);
    }

    #[test]
    fn with_tmpfs_over_bind() {
        let mut config = base_config();
        config.extra_volumes = vec![
            MountSpec::bind("/home/u/.claude", "/root/.claude"),
            MountSpec::tmpfs("/root/.claude/plugins"),
        ];
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("target: \"/root/.claude/plugins\""));
        assert!(yaml.contains("type: tmpfs"));
    }

    #[test]
    fn with_readonly_bind() {
        let mut config = base_config();
        config.extra_volumes = vec![MountSpec::bind("/a", "/a").read_only()];
        let yaml = generate_override_yaml(&config);
        assert!(yaml.contains("read_only: true"));
    }

    #[test]
    fn empty_extra_volumes_does_not_alter_existing_yaml() {
        // Sanity: the pre-existing minimal_override snapshot must still apply.
        let config = base_config();
        let yaml = generate_override_yaml(&config);
        assert!(!yaml.contains("type: bind"));
        assert!(!yaml.contains("type: tmpfs"));
        // Agent volume short-form line is still present.
        assert!(yaml.contains("cella-agent:/cella:ro"));
    }
}
